Infracciones.Administracion/Controllers/FraccionController.cs
using Infracciones.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Infracciones.Administracion.Controllers
{
    public class FraccionController : Controller
    {
        // GET: Fraccion
        public ActionResult Index()
        {
            return View();
        }

        // GET: Fraccion/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Fraccion/Create/{articuloId}
        public ActionResult Create(int id)
        {
            ViewBag.Articulo = ArticuloBl.Get(id);

            return View();
        }

        // POST: Fraccion/Create
        [HttpPost]
        public ActionResult Create(Fraccion fraccion)
        {
            try
            {
                if (Session["Usuario"] == null)
                    return RedirectToAction("Login", "Home");

                fraccion.UsuarioIdAlta = (Session["Usuario"] as Usuario).Id;
                if (ModelState.IsValid)
                {
                    FraccionBl.Add(fraccion);
                    return RedirectToAction($"Details/{fraccion.ArticuloId}","Articulo");
                }
                else
                {
                    ViewBag.Articulo = ArticuloBl.Get(fraccion.ArticuloId);
                    return View();
                }

            }
            catch
            {
                return View();
            }
        }

        // GET: Fraccion/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Fraccion/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Fraccion/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Fraccion/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Infracciones.Administracion/Views/Shared/Fraccion/_ListaDeFracciones.cshtml
@model IEnumerable<Infracciones.Dto.Fraccion>
<div class="container-fluid">
    <h3>Lista de fracciones</h3>
    <p>
        @Html.ActionLink("Agregar", $"Create/{ViewBag.ArticuloId}", "Fraccion")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Numero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaDeRegistro)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Numero)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaDeRegistro)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", "Fraccion", new { id = item.Id }, null) |
                    @*@Html.ActionLink("Editar", "Edit", "Fraccion", new { id = item.Id }, new { @class = "btn btn-success" }) |*@
                    @Html.ActionLink("Detalles", "Details", "Fraccion", new { id = item.Id }, null) |
                    @Html.ActionLink("Borrar", "Delete", "Fraccion", new { id = item.Id }, null)
                </td>
            </tr>
        }

    </table>

</div>